project_id = "skcgdoiestzqxsooaxur"

[functions.google-auth]
verify_jwt = false

[functions.google-calendar]
verify_jwt = false

[functions.google-gmail]
verify_jwt = false

[functions.vertex-ai]
verify_jwt = false

[functions.portal-validate]
verify_jwt = false

[functions.asana-service]
verify_jwt = false

[functions.calculate-family-fee-tier]
verify_jwt = false
