
ALTER TABLE public.sovereignty_charters
  ADD COLUMN IF NOT EXISTS transition_summary text,
  ADD COLUMN IF NOT EXISTS primary_goal text,
  ADD COLUMN IF NOT EXISTS long_term_strategy text,
  ADD COLUMN IF NOT EXISTS roles_responsibilities text,
  ADD COLUMN IF NOT EXISTS withdrawal_safeguards text,
  ADD COLUMN IF NOT EXISTS secondary_quiet_period_rule text,
  ADD COLUMN IF NOT EXISTS professional_coordination text,
  ADD COLUMN IF NOT EXISTS monitoring_cadence text,
  ADD COLUMN IF NOT EXISTS growth_primary_label text,
  ADD COLUMN IF NOT EXISTS growth_primary_value numeric,
  ADD COLUMN IF NOT EXISTS growth_primary_detail text,
  ADD COLUMN IF NOT EXISTS growth_secondary_label text,
  ADD COLUMN IF NOT EXISTS growth_secondary_value numeric,
  ADD COLUMN IF NOT EXISTS growth_secondary_detail text,
  ADD COLUMN IF NOT EXISTS storehouse_liquidity_detail text,
  ADD COLUMN IF NOT EXISTS storehouse_liquidity_value numeric,
  ADD COLUMN IF NOT EXISTS storehouse_strategic_detail text,
  ADD COLUMN IF NOT EXISTS storehouse_strategic_value numeric,
  ADD COLUMN IF NOT EXISTS storehouse_philanthropic_detail text,
  ADD COLUMN IF NOT EXISTS storehouse_legacy_detail text,
  ADD COLUMN IF NOT EXISTS harvest_review_date text,
  ADD COLUMN IF NOT EXISTS harvest_target_income numeric,
  ADD COLUMN IF NOT EXISTS harvest_yield_protocol text,
  ADD COLUMN IF NOT EXISTS harvest_spending_categories text,
  ADD COLUMN IF NOT EXISTS executor_primary text,
  ADD COLUMN IF NOT EXISTS executor_alternate text,
  ADD COLUMN IF NOT EXISTS succession_terms text,
  ADD COLUMN IF NOT EXISTS ratification_signatories jsonb NOT NULL DEFAULT '[]'::jsonb;
